### ISSUE TITLE
Feature: Need to add Footer in the website!

### ISSUE THREAD

**Issue by nayandas123** [Google-Developer-Student-Club-RJIT/Donaate#13]
Propose changes:
- I'll add a footer.
- I'll also add a socials section inside the footer

**Comment by mr-palindrome** [comment]
You can proceed!

**Comment by Hiresh23** [comment]
i would like to contribute ,please assign

**Comment by Dhruv031003** [comment]
Okay you can start the work.
Please follow the UI which you can find in the Readme.md file

**Comment by Hiresh23** [comment]
can you please add the hacktoberfest tag

**Comment by Hiresh23** [comment]
can you check the pull request i have followed the ui
