### ISSUE TITLE
Remove horizontal scrolling

### ISSUE THREAD

**Issue by Laxmankohar** [Google-Developer-Student-Club-RJIT/Donaate#25]
I would like to work on this issue.please assign this to me.
I opening this issue under hacktoberfest 2022.

![image](https://user-images.githubusercontent.com/73365025/196017276-3b32464a-0e2b-4d01-a2cb-673202dc58b7.png)

**Comment by Dhruv031003** [comment]
@Laxmankohar 
Okay you can work on this issue.
- It would be great if you use flex or grid instead of giving the div absolute property and then aligning it, as done earlier by the person who made it.

**Comment by Laxmankohar** [comment]
> @Laxmankohar Okay you can work on this issue.
> 
> * It would be great if you use flex or grid instead of giving the div absolute property and then aligning it, as done earlier by the person who made it.

I don't think there will be need of flexbox or grid to remove the horizontal scrolling.

**Comment by Laxmankohar** [comment]
I have made the changes and now there is no extra gap coming on the right side of web page.

![image](https://user-images.githubusercontent.com/73365025/196022644-462b16dc-784a-43b5-88d5-44bfcc9e50c6.png)

**Comment by Dhruv031003** [comment]
@Laxmankohar Okay raise the PR.
