### ISSUE TITLE
Hero image Stretching and font-style is not rendering

### ISSUE THREAD

**Issue by wherethehellami** [Google-Developer-Student-Club-RJIT/Donaate#27]
![Screenshot (45)](https://user-images.githubusercontent.com/80805143/196026026-69068379-69c5-47f4-8735-ad887291ca60.png)

can i work on this issue?

**Comment by mr-palindrome** [comment]
Hey @wherethehellami !
Thanks for showing interest. We have assigned a similar issue to someone else. But we have a similar issue for you in which you can work.

In the donate here section there are some issue with the alignment of the elements. You can fix them and create a PR. Here is the screenshot in a wide screen!
![image](https://user-images.githubusercontent.com/56421861/196044181-65877ba4-6735-4c99-9019-513546a93ffb.png)

**Comment by mr-palindrome** [comment]
At the same time you can also fix the hero image which is streaching!
