### ISSUE TITLE
Changes in navbar

### ISSUE THREAD

**Issue by mr-palindrome** [Google-Developer-Student-Club-RJIT/Donaate#30]
### Propose Changes

- [x] Add a home button before about button on navbar which will be inactive at the top.
- [x] Add functionality in navbar. The buttons are not clickable.
- [x] Add hover animation in the about, donation and faq buttons.

**Comment by Vanshika61** [comment]
I would like to work on this issue!

**Comment by manan18** [comment]
Can you please assign me this issue?

**Comment by Dhruv031003** [comment]
@manan18 This issue is already assigned to someone else. You can find any other issue to work or you can create an issue if you find one.

**Comment by Vanshika61** [comment]
![image](https://user-images.githubusercontent.com/97943080/196157817-4b08ba6a-d1d7-4fae-aaea-e1e5adb5870b.png)

Hey!
I have added all the functionalities according to the issue, You can check it.
