### ISSUE TITLE
Improve Responsiveness of Footer section.

### ISSUE THREAD

**Issue by Mahak008** [Google-Developer-Student-Club-RJIT/Donaate#35]

**Comment by Dhruv031003** [comment]
@Mahak008 Do you want to work on this issue??

**Comment by Dhruv031003** [comment]
@Mahak008 Okay you can start the work.

**Comment by Mahak008** [comment]
@Dhruv031003 I have been assigned this task. So, should I still revert back the changes.

**Comment by Dhruv031003** [comment]
@Mahak008 
No there is no need to revert the changes. The issues were different so I got confused.
Just update your code for the footer and then start working on the responsiveness.

**Comment by Mahak008** [comment]
> @Mahak008 No there is no need to revert the changes. The issues were different so I got confused. Just update your code for the footer and then start working on the responsiveness.

I have added the code for footer and responsiveness as well. Check it once please

**Comment by Dhruv031003** [comment]
@Mahak008 
Okay I will check it.
