### ISSUE TITLE
Acknowledge the Contributors by adding Contributors Section in README.md

### ISSUE THREAD

**Issue by mr-palindrome** [Google-Developer-Student-Club-RJIT/Donaate#4]
### Proposed Changes

- Add a dynamic Contributors Section in README file
- Add Copyright Logo to the Project at end of README
- Add more helpful links for beginners in Contributing.md (if needed)

**Comment by Aman0307** [comment]
@mr-palindrome I would like to contribute to this issue.

**Comment by mr-palindrome** [comment]
> @mr-palindrome I would like to contribute to this issue.

Yeah sure @Aman0307. Go ahead!
But keep in mind that we need a dynamic contributors section which will automatically get updated!

**Comment by mr-palindrome** [comment]
Hey @Aman0307 !
You can take reference from here https://contrib.rocks/preview?repo=Google-Developer-Student-Club-RJIT%2Fdonaate

**Comment by mr-palindrome** [comment]
Hey @Aman0307 !
Are you still working on this issue? Do you need any help?

**Comment by thisisamish** [comment]
Hey! I would love to work on this. :)

**Comment by mr-palindrome** [comment]
> @mr-palindrome I cannot give time to this issue currently(As I am occupied with some other work). I know how to add contributors section but I have no idea about how to make it dynamic so that it gets updated automatically. Please assign it to someone else if they are interested. Thanks.

No problem!

**Comment by mr-palindrome** [comment]
> Hey! I would love to work on this. :)

Yeah go ahead!

**Comment by Dhruv031003** [comment]
@thisisamish Any updates??

**Comment by thisisamish** [comment]
@Dhruv031003 got my exams this week, so i need a bit more time. :)

**Comment by Dhruv031003** [comment]
@thisisamish No issues. Just make it as soon as possible.

**Comment by su-shubham** [comment]
Can I work on it?

**Comment by Dhruv031003** [comment]
@su-shubham
 It's already assigned to him. You can if @thisisamish agrees for it.
