### ISSUE TITLE
About video features

### ISSUE THREAD

**Issue by su-shubham** [Google-Developer-Student-Club-RJIT/Donaate#49]
I think instead of showing link we can represent in the form of video at the donateHere section.

**Comment by Dhruv031003** [comment]
@su-shubham 
This site is currently at an early stage and we don't have videos or images of any kind so for now we are keeping links.
Thanks for the idea, we will consider adding this in the upcoming future.

Do visit the Youtube links present in Donate here section😁😁

**Comment by su-shubham** [comment]
Oh! Okay, can I make it possible?

**Comment by Dhruv031003** [comment]
I'll have to discuss this with my team. I will revert you by tomorrow

**Comment by Dhruv031003** [comment]
@su-shubham 
Sorry for the late reply.
Yes you can work on this.
Please Keep the UI in mind.
Before that please give a brief description of what you will be doing

**Comment by su-shubham** [comment]
Actually there will be form and video section so I will work first on form section where section display form and the form connected with our database where we basically get the data about the information that user want to put and basically for video section we should have to include youtube video so we can show video instead of having just lossy links. That's what my point to improve this project.
