### ISSUE TITLE
Setup a issue template

### ISSUE THREAD

**Issue by su-shubham** [Google-Developer-Student-Club-RJIT/Donaate#50]
Issue template should be there it make sense if someone want's to open issues.

**Comment by Dhruv031003** [comment]
@su-shubham 
If you want to work on this you can start the work.

**Comment by su-shubham** [comment]
One of maintainer have take look into this https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository inorder to use issue template.

**Comment by su-shubham** [comment]
I am Happy to close this issue! 🙂

**Comment by Dhruv031003** [comment]
Happy deepawali @su-shubham 
Thanks for the suggestion I will surely look into this.

**Comment by su-shubham** [comment]
Happy Diwali ! Have a nice day
