### ISSUE TITLE
Gdsc issues

### ISSUE THREAD

**Issue by Deadshot031003** [Google-Developer-Student-Club-RJIT/Donaate#51]
This is an empty issue

**Comment by Vaishnavi-More** [comment]
Hey! Will you kindly let me know what is the issue?

**Comment by Dhruv031003** [comment]
@Vaishnavi-More
We had a session in which we taught students about Git and Github. 
This was a example/sample issue to show students how issues are made, assigned and resolved.

**Comment by Vaishnavi-More** [comment]
Okay! 
Thank You once again!
