### ISSUE TITLE
Want to edit in donaate project

### ISSUE THREAD

**Issue by priyasingh2005** [Google-Developer-Student-Club-RJIT/Donaate#56]
Sir we can add "donate books " option in donate here because the children also want education to change their future and the existing world.

**Comment by Dhruv031003** [comment]
@priyasingh2005 
That is a great idea Priya, You can add this in the Donate here section besides donate clothes and money.
If you have any other such idea you can add that too and make it a 2x2 grid.
- Please keep the format same as in the UI.

**Comment by Dhruv031003** [comment]
@priyasingh2005 
There is no need to address by using Sir/Maam/etc , we all are equal here.

Welcome to Github and Open Source, I hope you have a Great time here.
All the best for your first contribution and the future here as well.

**Comment by priyasingh2005** [comment]
I would not be able to work on this issue due to certain issues  in my pc.

**Comment by Dhruv031003** [comment]
Okay @priyasingh2005

**Comment by Utkarsh404-crypto** [comment]
Hey! @Dhruv031003 I would like to add some options in the donation section. Can you assign me this task?

**Comment by Dhruv031003** [comment]
Happy Deepawali @Utkarsh404-crypto 

I will assign it to you.
Can you give a brief description of what options you will be adding.

**Comment by Utkarsh404-crypto** [comment]
Happy Diwali @Dhruv031003 
I will add donate grocery items and donate books in the donation section and will think for more.

**Comment by Dhruv031003** [comment]
@Utkarsh404-crypto please solve the issues with your PR or I will assign this to someone else

**Comment by Utkarsh404-crypto** [comment]
@Dhruv031003 Sure! I will do it by today.
