### ISSUE TITLE
Enhance the navbar, color scheme and add some images

### ISSUE THREAD

**Issue by SonamGiri9150** [Google-Developer-Student-Club-RJIT/Donaate#58]

**Comment by SonamGiri9150** [comment]
I would like to work on this 
Please assign me to this task

**Comment by Dhruv031003** [comment]
@SonamGiri9150 
The enhancment and color change should be according to the UI present in the README.
Please give a description of images which you will add.

**Comment by SonamGiri9150** [comment]
@Dhruv031003 I would keep in mind the UI 
The images I am thinking of adding are related to donation activities only

**Comment by Dhruv031003** [comment]
@SonamGiri9150 
Okay, the images should be free to use and copyright free.
