### ISSUE TITLE
Unwanted space above footer

### ISSUE THREAD

**Issue by Dhruv031003** [Google-Developer-Student-Club-RJIT/Donaate#67]
![image](https://user-images.githubusercontent.com/91516121/198282076-6d327eb0-afef-4d8b-9777-e6fe6517007c.png)
There is an unwanted space between `footer` and `Contact Us` section. Remove the space.

**Comment by Ayushsahrawat** [comment]
i want to work on this issue

**Comment by hanajiffry99** [comment]
Can you please assign this task to me, I can fix it.

**Comment by Dhruv031003** [comment]
@hanajiffry99, @Ayushsahrawat asked first so I am assigning this to him
