### ISSUE TITLE
Center align the hero section

### ISSUE THREAD

**Issue by vikrammahto** [Google-Developer-Student-Club-RJIT/Donaate#9]
![Donaate](https://user-images.githubusercontent.com/47027476/194815059-acf626f8-d16a-4604-833f-9b7e7bc1cf1b.png)

**Comment by mr-palindrome** [comment]
Hey @vikrammahto!
There is already a issue which is related to this issue #8 

You can create any other ticket!

**Comment by vikrammahto** [comment]
Ok thank you.
